apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: worker
          image: 921647845311.dkr.ecr.eu-west-1.amazonaws.com/stats:arm64v7
          args:
            - bot
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr
---
apiVersion: v1
kind: Service
metadata:
  name: bot
spec:
  selector:
    app: bot
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bot
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`stats-bot.yuseinishiyama.com`) && PathPrefix(`/webhook`)
      kind: Rule
      services:
        - name: bot
          port: 80
  tls:
    secretName: tls-bot
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bot-staging
spec:
  secretName: tls-bot-staging
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - stats-bot.yuseinishiyama.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bot
spec:
  secretName: tls-bot
  issuerRef:
    group: cert-manager.io
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - stats-bot.yuseinishiyama.com
