apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: worker
          image: 921647845311.dkr.ecr.eu-west-1.amazonaws.com/stats:arm64v7
          args:
            - bot
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr
