apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: worker
              # multi-arch manifest doesn't work
              # image: 921647845311.dkr.ecr.eu-west-1.amazonaws.com/stats:latest
              image: 921647845311.dkr.ecr.eu-west-1.amazonaws.com/stats:arm64v7
              args:
                - worker
          restartPolicy: Never
          imagePullSecrets:
            - name: ecr
